### PR TITLE
SNOW-902709 Limit the max allowed number of chunks in blob

### LINKED ISSUE #567: `registerBlobs` does not limit the size of the blobs request
Unfortunately, it looks like when a blob register request fails and the size of the blob request increases dramatically due to the backoff, the client is not pruning the request to fit within whatever size limit that is being specified by the backend.

```
  Aug 10, 2023 @ 14:38:54.678	[SF_INGEST] Start registering blobs in client=snowflake_ingest, totalBlobListSize=94, currentBlobListSize=94, idx=94
	Aug 10, 2023 @ 14:38:55.048	Retrying request to {tls}->http://******************************->https://***************************************
	Aug 10, 2023 @ 14:38:55.048	I/O exception (java.net.SocketException) caught when processing request to {tls}->http://***********************->https://*****************************: Connection reset by peer
	Aug 10, 2023 @ 14:38:55.048	Retrying request which caused java.net.SocketException with URI:/v1/streaming/channels/write/blobs/, retryCount:1 and maxRetryCount:10
	Aug 10, 2023 @ 14:38:55.199	Exceptional Status Code from STREAMING_REGISTER_BLOB: 413, requestId:
	Aug 10, 2023 @ 14:38:55.200	[SF_INGEST] Background flush task failed, client=snowflake_ingest, exception=net.snowflake.ingest.utils.SFException: Register blob request failed: HTTP Status: 413 ErrorBody: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
</body>
</html>
., detail=Register blob request failed: HTTP Status: 413 ErrorBody: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
</body>
</html>
., trace=
net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal.registerBlobs(SnowflakeStreamingIngestClientInternal.java:462)
net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal.registerBlobs(SnowflakeStreamingIngestClientInternal.java:417)
net.snowflake.ingest.streaming.internal.RegisterService.registerBlobs(RegisterService.java:199)
net.snowflake.ingest.streaming.internal.FlushService.lambda$registerFuture$2(FlushService.java:244)
java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base/java.lang.Thread.run(Thread.java:833).
```

This makes sense because it looks like the client yeets in the blob metadata with abandon.

https://github.com/snowflakedb/snowflake-ingest-java/blob/29993909bf164059829062dc39944b0908c7ec8c/src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java#L452

I suspect I'm hitting this issue due to how many blobs are being created within a client.

### LINKED ISSUE #570: Only flush channels for tables with a channel that needs flushing rather than flushing all channels for all tables
DISCLAIMER: This is based on my interpretation of the SDK, still getting up to speed on the internals.

Currently the SDK attempts to flush all channels on an interval, instead, would it be possible and potentially more efficient to only flush channels where the rowbuffer has hit the expected size? In high volume/high channel count use cases the SDK has to flush a large number of blobs after every time period.

For example, if we have 100 channels, and a flush interval of 1 second where each channel receives at least 1 row per second. Then the SDK will attempt to flush 100 chunks every second. Even if the flush interval is increased to 60 seconds, if a single channel in our list of 100 channels needs flushing once per second because it is higher volume than remaining channels, then the SDK will still attempt to flush 100 chunks every second.

Instead, if the `FlushService` is refactored such that it knows which tables/channels need to be flushed then the number of chunks being pushed can be reduced. Taking the example above where there exist 100 channels, with a single channel needing to be flushed every second, with a force flush interval of 60 seconds. There should ideally be 1 chunks being pushed every second (assuming the rowbuffers stack to a single blob), rather than 100 chunks.

e2: Potentially there is scope to have the interval be per table so that regularly flushing tables don't need to be force flushed as part of the flush cycle which could potentially help with increasing size of the blobs being pushed, assuming that bigger blobs are better. This would also help avoiding the glut of requests/volume when flushing on the interval.

My understanding is that this should be okay, as ordering is only preserved within channels, so processing data out of order is okay across different tables.

I understand this might be a fairly big refactor of some of the SDK, would be keen to hear your thoughts or whether I am off track with my understanding of the code. I'm hoping this helps with some of the issues I've seen with high blob counts causing networking errors.

e: I'm also happy to provide an implementation/PR for this with guidance if this isn't going to be prioritized.

e3: Blob -> Chunk

### PR DESCRIPTION
**Pull request by sfc-gh-lsembera**
When one client is ingesting into many tables, we are seeing occasional timeouts from blob registrations calls. This PR introduces the limit of 20 chunks in one blob and in blob registration request.

Fixes #570
Fixes #567

### CODE REVIEW

File: src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java [hunk 1]
```diff
@@ -452,7 +452,42 @@ ChannelsStatusResponse getChannelsStatus(
...
+    List<BlobMetadata> currentBatch = new ArrayList<>();
+    int chunksInCurrentBatch = 0;
+
+    for (BlobMetadata blob : blobs) {
+      if (chunksInCurrentBatch + blob.getChunks().size()
+          > parameterProvider.getMaxChunksInRegistrationRequest()) {
+        // Newly added BDEC file would exceed the max number of chunks in a single registration
+        // request. We put chunks collected so far into the result list and create a new batch with
+        // the current blob
+        result.add(currentBatch);
```
Comment (sfc-gh-asen) [inline src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java:475]: nit: This probably can't happen as long as `maxChunksInBlob` parameter is less than `getMaxChunksInRegistrationRequest` parameter but if it is not we will add a `currentBatch` that is empty to the `result` list.

File: src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java [hunk 2]
```diff
@@ -351,6 +351,16 @@ void distributeFlushTasks() {
...
+        } else if (blobData.size()
+            >= this.owningClient.getParameterProvider().getMaxChunksInBlob()) {
+          // Create a new blob if the current one already contains max allowed number of chunks
+          logger.logInfo(
+              "Max allowed number of chunks in the current blob reached. chunkCount={}"
+                  + " maxChunkCount={} currentBlobPath={}",
+              blobData.size(),
+              this.owningClient.getParameterProvider().getMaxChunksInBlob(),
+              blobPath);
+          break;
```
Comment (sfc-gh-asen) [inline src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java:363]: Should this check be in the shouldStopProcessing() method? 

if I am not wrong if the leftoverChannelsDataPerTable is not empty, then we will ignore this check

File: src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java [hunk 3]
```diff
@@ -351,6 +351,16 @@ void distributeFlushTasks() {
         if (!leftoverChannelsDataPerTable.isEmpty()) {
           channelsDataPerTable.addAll(leftoverChannelsDataPerTable);
           leftoverChannelsDataPerTable.clear();
+        } else if (blobData.size()
```
Comment (sfc-gh-tzhang) [inline src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java:354]: Could the logic here combined with https://github.com/snowflakedb/snowflake-ingest-java/blob/3a3cbc8798e2e4eddab1cc672b9d48d557e48d78/src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java#L407? Both are checking whether a separate blob is needed

File: src/main/java/net/snowflake/ingest/utils/ParameterProvider.java [hunk 4]
```diff
@@ -46,6 +49,8 @@ public class ParameterProvider {
   public static final long MAX_CHANNEL_SIZE_IN_BYTES_DEFAULT = 32000000L;
   public static final long MAX_CHUNK_SIZE_IN_BYTES_DEFAULT = 128000000L;
   public static final long MAX_ALLOWED_ROW_SIZE_IN_BYTES_DEFAULT = 64 * 1024 * 1024; // 64 MB
+  public static final int MAX_CHUNKS_IN_BLOB_DEFAULT = 20;
+  public static final int MAX_CHUNKS_IN_REGISTRATION_REQUEST_DEFAULT = 100;
```
Comment (sfc-gh-tzhang) [inline src/main/java/net/snowflake/ingest/utils/ParameterProvider.java:53]: What is the real issue here? Is it because of the total number of chunks in one blob or the total number of the chunks in one request? If it's former, then why we need to limit the total number of chunks in one request? If it's latter, then these two values should be the same?

**Review by sfc-gh-tzhang — COMMENTED** [review]
Left some comment, PTAL! No need to block on my approval :)

File: src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java (hunk 2 above)
Comment (sfc-gh-tzhang) [reply src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java:363]: I think shouldStopProcessing is checking on the channel level but this is on the chunks level, there is no correctness issue if leftoverChannelsDataPerTable is not empty, right?

File: src/main/java/net/snowflake/ingest/utils/ParameterProvider.java (hunk 4 above)
Comment (sfc-gh-lsembera) [reply src/main/java/net/snowflake/ingest/utils/ParameterProvider.java:53]: Fundamentally, the issue issue is the number of chunks in one request, because it is where the server-side latency and potential timeouts come from. They could be the same, the reasoning behind one being smaller than the other was that it would give the SDK an oportunity to put BDECs with fewer chunks into the same registration request. For example, if the limit of both is 100 and there is another bdec with just one chunk, it would have to go into its own registration request.

File: src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java (hunk 3 above)
Comment (sfc-gh-lsembera) [reply src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java:354]: It could, but it could be triggered in the middle of a chunk, which is makes sense for splitting based on chunk/blob size, but not for the newly added check. The only added check only cares about the number of chunks in a blob, so I put the potential break just before it starts a new chunk.

File: src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java (hunk 2 above)
Comment (sfc-gh-lsembera) [reply src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java:362]: Additional test added to `FlushServiceTest`

File: src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java (hunk 1 above)
Comment (sfc-gh-lsembera) [reply src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java:475]: Good point, I added validation that `maxChunksInBlob` is always less than `getMaxChunksInRegistrationRequest`

File: src/main/java/net/snowflake/ingest/utils/ParameterProvider.java [hunk 5]
```diff
@@ -30,6 +30,9 @@ public class ParameterProvider {
   public static final String MAX_CHUNK_SIZE_IN_BYTES = "MAX_CHUNK_SIZE_IN_BYTES".toLowerCase();
   public static final String MAX_ALLOWED_ROW_SIZE_IN_BYTES =
       "MAX_ALLOWED_ROW_SIZE_IN_BYTES".toLowerCase();
+  public static final String MAX_CHUNKS_IN_BLOB = "MAX_CHUNKS_IN_BDEC".toLowerCase();
```
[the remark this answers is not in the document]
Comment (sfc-gh-lsembera) [reply src/main/java/net/snowflake/ingest/utils/ParameterProvider.java]: Unit tests added

**Comment by sfc-gh-lsembera** [comment]
@sfc-gh-tzhang I addressed your PR comments, could you re-review, please?

File: src/main/java/net/snowflake/ingest/utils/ParameterProvider.java (hunk 4 above)
Comment (sfc-gh-tzhang) [reply src/main/java/net/snowflake/ingest/utils/ParameterProvider.java:66]: I see, given that this situation should be rare, I'm not sure if we need to be smart here. I'm more in a favor of adding less configurable parameters with random default values, WDYT?

**Review by sfc-gh-tzhang — APPROVED** [review]
Left a suggestion, PTAL and feel free to merge if you disagree, thanks!
